WebPhongVu_DoAnWeb/WebBanHang/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;
using System.Threading.Tasks;

namespace WebBanHang.Controllers
{
    public class TrangChuController : Controller
    {
        private QLBH_QLDA_HTMmartEntities1 db = new QLBH_QLDA_HTMmartEntities1();

        // GET: TrangChu
        private readonly IChatbotService twilioChatService;

        public TrangChuController(IChatbotService twilioChatService)
        {
            this.twilioChatService = twilioChatService;
        }

        [HttpPost]
        public async Task<ActionResult> GetChatbotResponse(string userMessage)
        {
            try
            {
                // Call the TwilioChatService to get a response
                string chatbotResponse = await twilioChatService.GetChatbotResponse(userMessage);

                // Return the response as JSON
                return Json(new { response = chatbotResponse });
            }
            catch (Exception ex)
            {
                // Handle exceptions and return an error response
                return Json(new { error = ex.Message });
            }
        }

        // Example of sending an SMS message
        [HttpPost]
        public async Task<ActionResult> SendMessage(string toPhoneNumber, string message)
        {
            try
            {
                // Call the TwilioChatService to send an SMS message
                await twilioChatService.SendMessageAsync(toPhoneNumber, message);

                // Return success response
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                // Handle exceptions and return an error response
                return Json(new { error = ex.Message });
            }
        }



        public ActionResult SortProducts(string sortOrder)
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSP);

            switch (sortOrder)
            {
                case "desc":
                    sanPhams = sanPhams.OrderByDescending(item => item.DonGia);
                    break;
                case "asc":
                default:
                    sanPhams = sanPhams.OrderBy(item => item.DonGia);
                    break;
            }

            return PartialView("_ProductList", sanPhams.ToList());
        }

        public ActionResult Index()
        {
            var sanPhams = db.SanPhams.Include(s => s.LoaiSP);
            return View(sanPhams.ToList());
        }



        // GET: TrangChu/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: TrangChu/Create
        public ActionResult Create()
        {
            ViewBag.MaSLP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP");
            return View();
        }

        // POST: TrangChu/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,AnhSP,DVT,DonGia,MoTaSP,MaSLP")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.SanPhams.Add(sanPham);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaSLP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", sanPham.MaSLP);
            return View(sanPham);
        }

        // GET: TrangChu/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaSLP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", sanPham.MaSLP);
            return View(sanPham);
        }

        // POST: TrangChu/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,AnhSP,DVT,DonGia,MoTaSP,MaSLP")] SanPham sanPham)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaSLP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", sanPham.MaSLP);
            return View(sanPham);
        }

        // GET: TrangChu/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: TrangChu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebPhongVu_DoAnWeb/WebBanHang/Views/TrangChu/Index.cshtml
    @model List<WebBanHang.Models.SanPham>

    @{
        ViewBag.Title = "Index";
        Layout = "~/Views/Shared/_LayoutGuest.cshtml";

        // Sort direction: true for ascending (cheapest to most expensive), false for descending
        bool sortAscending = true;

        // Sort the model based on the DonGia property
        var sortedModel = sortAscending
            ? Model.OrderBy(item => item.DonGia)
            : Model.OrderByDescending(item => item.DonGia);
    }

    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div id="productContainer">
                    @Html.Partial("_ProductList", sortedModel)
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label for="sortOrder">Sort Order:</label>
                    <select id="sortOrder" class="form-control" onchange="sortProducts()">
                        <option value="asc">Cheapest to Most Expensive</option>
                        <option value="desc">Most Expensive to Cheapest</option>
                    </select>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        function sortProducts() {
        var sortOrder = $("#sortOrder").val();
        var url = "@Url.Action("SortProducts", "TrangChu")";

        $.ajax({
            url: url,
            type: "GET",
            data: { sortOrder: sortOrder },
            success: function (result) {
                $("#productContainer").html(result);
            },
            error: function (error) {
                console.log(error);
            }
        });
    }

    </script>

WebPhongVu_DoAnWeb/WebBanHang/Views/TrangChu/_ProductList.cshtml
@model IEnumerable<WebBanHang.Models.SanPham>

    @foreach (var item in Model)
    {
    <div class="card col-md-3 text-center">
        <div class="card-block">
            <h4 class="card-title">@item.TenSP</h4>
            <img src="~/Public/Images/@item.AnhSP" style="width:150px; height:150px" class="text-center card-img-top img-fluid" alt="...">
            <p class="card-text" style="height: 3em; overflow: hidden; text-overflow: ellipsis;">@item.MoTaSP</p>
            <p>Đơn vị tính: @item.DVT</p>
            <p>Giá: @(item.DonGia.HasValue ? item.DonGia.Value.ToString("#,##0").Replace(',', '.') : "N/A") VNĐ</p>
            <a href="@Url.Action("ThemVaoGio", "GioHangs" , new { MaSP=item.MaSP })" id="btnAddToCart" onclick="AddtoCart(this)" class="btn btn-primary"><i class="fas fa-shopping-cart"></i>Thêm vào giỏ hàng</a>
        </div>
    </div>
    }