WebPhongVu_DoAnWeb/WebBanHang/Models/NhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public string MaNCC { get; set; }
        public string TenNCC { get; set; }
        public string DiaChi { get; set; }
        public string SDT_NCC { get; set; }
        public string Email { get; set; }
        public string MLSP { get; set; }
    
        public virtual LoaiSP LoaiSP { get; set; }
    }
}

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Controllers/NhaCungCapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class NhaCungCapsController : Controller
    {
        private QLBH_QLDA_HTMmartEntities1 db = new QLBH_QLDA_HTMmartEntities1();

        // GET: Admin/NhaCungCaps
        public ActionResult Index()
        {
            var nhaCungCaps = db.NhaCungCaps.Include(n => n.LoaiSP);
            return View(nhaCungCaps.ToList());
        }

        // GET: Admin/NhaCungCaps/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Create
        public ActionResult Create()
        {
            ViewBag.MLSP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP");
            return View();
        }

        // POST: Admin/NhaCungCaps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNCC,TenNCC,DiaChi,SDT_NCC,Email,MLSP")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                db.NhaCungCaps.Add(nhaCungCap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MLSP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", nhaCungCap.MLSP);
            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            ViewBag.MLSP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", nhaCungCap.MLSP);
            return View(nhaCungCap);
        }

        // POST: Admin/NhaCungCaps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNCC,TenNCC,DiaChi,SDT_NCC,Email,MLSP")] NhaCungCap nhaCungCap)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhaCungCap).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MLSP = new SelectList(db.LoaiSPs, "MaLSP", "TenLSP", nhaCungCap.MLSP);
            return View(nhaCungCap);
        }

        // GET: Admin/NhaCungCaps/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // POST: Admin/NhaCungCaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            db.NhaCungCaps.Remove(nhaCungCap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhaCungCaps/Create.cshtml
@model WebBanHang.Models.NhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <div class="bg-info py-2">
        <h4 class="text-white text-center"><strong>Thêm nhà cung cấp</strong></h4>
    </div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <label>Mã Nhà Cung Cung cấp</label>
        @Html.TextAreaFor(model => model.MaNCC, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <label>Tên Nhà Cung Cấp</label>
            @Html.TextAreaFor(model => model.TenNCC, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Địa Chỉ</label>
        @Html.TextAreaFor(model => model.DiaChi, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        <label>SĐT Nhà Cung Cấp</label>
        @Html.TextAreaFor(model => model.SDT_NCC, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.SDT_NCC, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Email Nhà Cung Cấp</label>
        @Html.TextAreaFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <label>Mã loại sản phẩm</label>
        @Html.DropDownListFor(model => model.MLSP, (SelectList)ViewBag.ListMaLSP, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MLSP, "", new { @class = "text-danger" })
    </div>
</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
   
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhaCungCaps/Delete.cshtml
@model WebBanHang.Models.NhaCungCap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<div class="alert alert-warning">
    <strong>Are you sure you want to delete this?</strong>
</div>
<div>
    <h4>Nhà cung cấp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Tên nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            <label>Địa chỉ nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            <label>SĐT Nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT_NCC)
        </dd>

        <dt>
            <label>Email nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            <label>Tên loại sản phẩm</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLSP)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhaCungCaps/Details.cshtml
@model WebBanHang.Models.NhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi Tiết</h2>

<div>
    <h4>Nhà Cung Cấp</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Tên nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNCC)
        </dd>

        <dt>
            <label>Địa chỉ nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            <label>SĐT Nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT_NCC)
        </dd>

        <dt>
            <label>Email nhà cung cấp</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            <label>Tên loại sản phẩm</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiSP.TenLSP)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNCC }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhaCungCaps/Edit.cshtml
@model WebBanHang.Models.NhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chỉnh sửa nhà cung cấp</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label>Mã nhà cung cấp</label>
        <div class="col-md-12">
            @Html.EditorFor(model => model.MaNCC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Tên nhà cung cấp</label>
        <div class="col-md-12">
            @Html.EditorFor(model => model.TenNCC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenNCC, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>Địa chỉ cung cấp</label>
        <div class="col-md-12">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label>SĐT Nhà cung cấp</label>
        <div class="col-md-12">
            @Html.EditorFor(model => model.SDT_NCC, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SDT_NCC, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <label>Email nhà cung cấp</label>
        <div class="col-md-12">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>

        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhaCungCaps/Index.cshtml
@model IEnumerable<WebBanHang.Models.NhaCungCap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card">
    <div class="card-header bg-info">
        <div class="row">
            <div class="col-md-6 ">
                <strong class="text-uppercase text-danger ">Danh sách nhà cung cấp</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create", "NhaCungCaps")" class="btn btn-sm btn-success">
                    <i class="fa-solid fa-plus"></i>Thêm
                </a>
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th style="width:20px;" class="text-center">#</th>
                    <th style="width:20px;" class="text-center">ID</th>
                    <th>Tên nhà cung cấp</th>
                    <th>Địa chỉ</th>
                    <th>SĐT NCC</th>
                    <th>Email NCC</th>
                    <th style="width:180px;" class="text-center">Chức năng</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">
                            <input name="checkID" type="checkbox" />
                        </td>
                        <td class="text-center">@item.MaNCC</td>
                        <td>@item.TenNCC</td>
                        <td>@item.DiaChi</td>
                        <td>@item.SDT_NCC</td>
                        <td>@item.Email</td>
                        <td class="text-center">
                            <a href="@Url.Action("Edit","NhaCungCaps", new {@id=item.MaNCC})" class="btn btn-sm btn-info"><i class="fa-solid fa-edit"></i></a>

                            <a href="@Url.Action("Details","NhaCungCaps", new {@id=item.MaNCC})" class="btn btn-sm btn-warning"><i class="fa-solid fa-circle-info"></i></a>

                            <a href="@Url.Action("Delete","NhaCungCaps", new {@id=item.MaNCC})" class="btn btn-sm btn-danger"> <i class="fa-solid fa-trash"></i></a>

                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>