WebPhongVu_DoAnWeb/WebBanHang/Models/NhanVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.GioHangs = new HashSet<GioHang>();
            this.GioHangs1 = new HashSet<GioHang>();
        }
    
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<bool> Administrator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs1 { get; set; }
    }
}

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Controllers/NhanViensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebBanHang.Models;

namespace WebBanHang.Areas.Admin.Controllers
{
    public class NhanViensController : Controller
    {
        private QLBH_QLDA_HTMmartEntities1 db = new QLBH_QLDA_HTMmartEntities1();

        // GET: Admin/NhanViens
        public ActionResult Index()
        {
            return View(db.NhanViens.ToList());
        }

        // GET: Admin/NhanViens/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NhanViens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,HoTen,NgaySinh,Email,MatKhau,GioiTinh,Administrator")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.NhanViens.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,HoTen,NgaySinh,Email,MatKhau,GioiTinh,Administrator")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nhanVien);
        }

        // GET: Admin/NhanViens/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanViens.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: Admin/NhanViens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhanVien nhanVien = db.NhanViens.Find(id);
            db.NhanViens.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhanViens/Create.cshtml
@model WebBanHang.Models.NhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="bg-info py-2">
            <h4 class="text-white text-center"><strong>Nhân viên</strong></h4>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatKhau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Administrator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Administrator)
                    @Html.ValidationMessageFor(model => model.Administrator, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhanViens/Delete.cshtml
@model WebBanHang.Models.NhanVien

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}
}

<h2>Delete</h2>

<div class="alert alert-warning">
    <strong>Are you sure you want to delete this?</strong>
</div>
<div>
    <h4>Nhân Viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Họ tên</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            <label>Ngày sinh</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            <label>Email</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            <label>Mật khẩu</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            <label>Giới tính</label>
        </dt>

        <dd>
            @{if (Model.GioiTinh == true)
                { gtinh = "Nam"; }
                else
                { gtinh = "Nữ"; }
            }
            @gtinh
        </dd>

        <dt>
            <label>Quyền admin</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Administrator)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhanViens/Details.cshtml
@model WebBanHang.Models.NhanVien

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}

<h2>Chi tiết</h2>

<div>
    <h4>Nhân Viên</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label>Họ tên</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            <label>Ngày sinh</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            <label>Email</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            <label>Mật khẩu</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            <label>Giới tính</label>
        </dt>

        <dd>
            @{if (Model.GioiTinh == true)
                { gtinh = "Nam"; }
                else
                { gtinh = "Nữ"; }
            }
            @gtinh
        </dd>

        <dt>
            <label>Quyền admin</label>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Administrator)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhanViens/Edit.cshtml
@model WebBanHang.Models.NhanVien

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            <label>Họ tên</label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Ngày sinh</label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Email</label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Mật khẩu</label>
            <div class="col-md-12">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label>Giới tính</label>
            <div class="col-md-12">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label>Quyền admin</label>
            <div class="col-md-12">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Administrator)
                    @Html.ValidationMessageFor(model => model.Administrator, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebPhongVu_DoAnWeb/WebBanHang/Areas/Admin/Views/NhanViens/Index.cshtml
@model IEnumerable<WebBanHang.Models.NhanVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}
<div class="card">
    <div class="card-header bg-info">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Danh sách nhân viên</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create", "NhanViens")" class="btn btn-sm btn-success">
                    Thêm
                </a>
            </div>
        </div>
    </div>
    <div class="card-body p-3">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th style="width:20px;" class="text-center">#</th>
                    <th>Mã nhân viên</th>
                    <th>Họ tên Nhân Viên</th>
                    <th>Ngày sinh</th>
                    <th>Email</th>
                    <th>Mật khẩu</th>
                    <th>Giới tính</th>
                    <th>Administrator</th>
                    <th style="width:180px;" class="text-center">Chức năng</th>

                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">
                            <input name="checkID" type="checkbox" />
                        </td>
                        <td>@item.MaNV</td>
                        <td>@item.HoTen</td>
                        <td>@item.NgaySinh</td>
                        <td>@item.Email</td>
                        <td>@item.MatKhau</td>
                        <td>
                            @{if (item.GioiTinh == true)
                                { gtinh = "Nam"; }
                                else
                                { gtinh = "Nữ"; }
                                                }
                                                @gtinh
                                            </td>
                        <td>@item.Administrator</td>
                        <td class="text-center">
                            <a href="@Url.Action("Edit","NhanViens", new {@id=item.MaNV})" class="btn btn-sm btn-info"><i class="fa-solid fa-edit"></i></a>

                            <a href="@Url.Action("Details","NhanViens", new {@id=item.MaNV})" class="btn btn-sm btn-warning"><i class="fa-solid fa-circle-info"></i></a>

                            <a href="@Url.Action("Delete","NhanViens", new {@id=item.MaNV})" class="btn btn-sm btn-danger"> <i class="fa-solid fa-trash"></i></a>

                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>